export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_CART_ITEMS: "ADD_CART_ITEMS",
  DECREASE_CART_ITEMS: "DECREASE_CART_ITEMS",
  DELETE_CART_ITEMS: "DELETE_CART_ITEMS",
};
